# Generated by Django 2.1.5 on 2019-02-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('contributor', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('geo_coord_original', models.CharField(max_length=100)),
                ('geo_coord_UTM', models.CharField(max_length=100)),
                ('period_date', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=200)),
                ('url_for_file', models.CharField(max_length=500)),
                ('verified_gps_coords', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
