# Generated by Django 2.1.5 on 2019-02-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slhpa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photorecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='photorecord',
            name='resource_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
