# Generated by Django 2.1.5 on 2019-02-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slhpa', '0003_auto_20190201_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photorecord',
            old_name='resource_number',
            new_name='resource_name',
        ),
    ]
