# Generated by Django 2.1.5 on 2019-02-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slhpa', '0004_auto_20190201_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photorecord',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
