# Generated by Django 2.1.5 on 2019-03-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slhpa', '0006_auto_20190212_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
    ]
