# Generated by Django 2.1.5 on 2019-03-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slhpa', '0007_keyvaluerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyvaluerecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='keyvaluerecord',
            name='key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
