# Generated by Django 2.1.5 on 2019-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slhpa', '0010_auto_20190308_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorecord',
            name='gps_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='photorecord',
            name='gps_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='photorecord',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
