# Generated by Django 2.1.5 on 2019-02-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('time_of_event', models.DateTimeField(primary_key=True, serialize=False, verbose_name='time-Of-Event')),
                ('photon1', models.IntegerField(blank=True, null=True)),
                ('photon2', models.IntegerField(blank=True, null=True)),
                ('photon3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
